name: testing

on: [push]

jobs:
  # for all tests
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
        id: go
      - name: check out
        uses: actions/checkout@v2

      # cache environment
      - name: Cache
        uses: actions/cache@v2.1.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  # build testing
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: cd server; go build -o samehada-db-server main.go

  # exec unit tests
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: change virtual file use flag to false
        run: sed -i "/EnableOnMemStorage/c const EnableOnMemStorage = false" lib/common/config.go
      - name: test
        run: cd lib; go test ./... -v -short
